# Generated by Django 3.2.23 on 2024-03-30 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tunes', '0003_auto_20240330_0953'),
    ]

    operations = [
        migrations.AlterField(
            model_name='watchlater',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
